### ISSUE TITLE
Unix-timestamp not working

### ISSUE THREAD

**Issue by pflik** [lswiderski/yet-another-garmin-connect-client#8]
Hi,

I've been using this client for a while now. (previously used the Bodycomposition client from David Kroell untill it stopped working).

What i notice is that the unix timestamp is not working correctly. It just uploads with the date and time of upload instead of the provided datetime stamp.

I'm using the command as follows:
YAGCC uploadbodycomposition --bmi 20.0  --bone-mass 3.0   --email XX@XX.Com --fat 20.5 --hydration 50.5 --metabolic-age 32 --muscle-mass 78.2 --password XX --physique-rating 2 --unix-timestamp 1717050449 --visceral-fat 5 --weight 90.5

That timestamp corresponds to 30th of May (to be precise Thursday, May 30, 2024 6:27:29 AM). But uploading it today just makes it show up on the 31th of May. I've tried this a couple of times, but garmin just shows it as being measured on the day of upload. 

Am i using the command wrong or is this feature not implemented?

**Comment by lswiderski** [comment]
Hi @pflik

I just checked your command and it works well for me. Bug with timestamp was fixed in November last year. Are you sure u use YAGCC in version 0.0.2 or 0.0.3?

Here is the result with date: 30 of May for timestamp 1717050449 
![image](https://github.com/lswiderski/yet-another-garmin-connect-client/assets/2623594/53f1a2e5-9bff-4687-b7a2-a553d5033779)

**Comment by pflik** [comment]
i just downloaded the last version, it seems to be working. Bit strange as the timestamp of the version i was using seems to from the 0.0.3 version, but alas this seems to be working now.
